In [ ]:
Assignment 9.ipynb

Text cell <8A5O0B6OzJMf>
#%% [markdown]
# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

Text cell <TMwNPgUzzJMk>
#%% [markdown]
#### Import NumPy as np

Code cell <fDgY9QxqzJMk>
#%% [code]


Text cell <tui6tu0YzJMl>
#%% [markdown]
#### Create an array of 10 zeros 

Code cell <D7pePmDqzJMl>
#%% [code]


Text cell <mAPcohujzJMl>
#%% [markdown]
#### Create an array of 10 ones

Code cell <oIf4w9zCzJMl>
#%% [code]


Text cell <zR2kFC_EzJMm>
#%% [markdown]
#### Create an array of 10 fives

Code cell <AnMTy9h8zJMm>
#%% [code]


Text cell <S_knGh2_zJMm>
#%% [markdown]
#### Create an array of the integers from 10 to 50

Code cell <MwcKcGtgzJMn>
#%% [code]


Text cell <sSkS5w3zzJMn>
#%% [markdown]
#### Create an array of all the even integers from 10 to 50

Code cell <-0JBle3UzJMo>
#%% [code]


Text cell <TIF6aCYXzJMo>
#%% [markdown]
#### Create a 3x3 matrix with values ranging from 0 to 8

Code cell <BeuEGj3SzJMo>
#%% [code]


Text cell <FXvF6OAtzJMo>
#%% [markdown]
#### Create a 3x3 identity matrix

Code cell <WSdpL7qzzJMo>
#%% [code]


Text cell <LUG29slSzJMo>
#%% [markdown]
#### Use NumPy to generate a random number between 0 and 1

Code cell <qDTGiLbizJMp>
#%% [code]


Text cell <jLlpCoUpzJMp>
#%% [markdown]
#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

Code cell <KHuQ8Wj0zJMp>
#%% [code]


Text cell <HOUFRIexzJMp>
#%% [markdown]
#### Create the following matrix:

Code cell <5uLN7mGezJMp>
#%% [code]


Text cell <8878yDRozJMq>
#%% [markdown]
 Create an array of 20 linearly spaced points between 0 and 1:

Code cell <3gEtEcIqzJMq>
#%% [code]


Text cell <YfYf93HyzJMq>
#%% [markdown]
## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

Code cell <_b52j7F7zJMq>
#%% [code]
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

Code cell <L3oB2nGKzJMq>
#%% [code]
mat = np.arange(1,26).reshape(5,5)
mat
Execution output
0KB
	text/plain
		array([[ 1,  2,  3,  4,  5],
		       [ 6,  7,  8,  9, 10],
		       [11, 12, 13, 14, 15],
		       [16, 17, 18, 19, 20],
		       [21, 22, 23, 24, 25]])

Code cell <S2MAY1RG1Khb>
#%% [code]
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

Code cell <2rRRhjgk1Khj>
#%% [code]

Execution output
0KB
	text/plain
		array([[12, 13, 14, 15],
		       [17, 18, 19, 20],
		       [22, 23, 24, 25]])

Code cell <YiuSm2GdzJMr>
#%% [code]
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

Code cell <DISUEBUQzJMr>
#%% [code]

Execution output
0KB
	text/plain
		20

Code cell <S7zOZdvmzJMr>
#%% [code]
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

Code cell <DGpPQCIvzJMr>
#%% [code]

Execution output
0KB
	text/plain
		array([[ 2],
		       [ 7],
		       [12]])

Code cell <xijEv0K2zJMr>
#%% [code]
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

Code cell <D0EGP1N3zJMs>
#%% [code]

Execution output
0KB
	text/plain
		array([21, 22, 23, 24, 25])

Code cell <eR9WZAMFzJMs>
#%% [code]
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

Code cell <dNVjyFtTzJMs>
#%% [code]

Execution output
0KB
	text/plain
		array([[16, 17, 18, 19, 20],
		       [21, 22, 23, 24, 25]])

Text cell <Pr_ft3KOzJMs>
#%% [markdown]
### Now do the following

Text cell <T2siLsbazJMs>
#%% [markdown]
#### Get the sum of all the values in mat

Code cell <raffxpZ_zJMs>
#%% [code]

Execution output
0KB
	text/plain
		325

Text cell <otPadDsYzJMs>
#%% [markdown]
#### Get the standard deviation of the values in mat

Code cell <vlwO3jKyzJMs>
#%% [code]

Execution output
0KB
	text/plain
		7.2111025509279782

Text cell <Ss6pdvnJzJMt>
#%% [markdown]
#### Get the sum of all the columns in mat

Code cell <qmGQOrhKzJMt>
#%% [code]

Execution output
0KB
	text/plain
		array([55, 60, 65, 70, 75])

Text cell <iBRdkB0fzJMt>
#%% [markdown]
# Great Job!


