In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.DataFrame(np.random.randn(5,5),index=['a','b','c','d','e'],columns=['p','q','r','s','t'])

In [ ]:
df


p         q         r         s         t
a -1.276265 -0.441164  1.088538  0.055988 -0.812554
b -0.207470  0.464722 -0.704728 -0.392833  1.024017
c  1.046727  0.369640 -0.859729 -0.272427 -0.595269
d -1.273295  0.558726 -0.784153  1.434853  0.587968
e  1.001514  0.213916  0.417707  0.180338 -0.784085

In [ ]:
df['p']

a   -1.276265
b   -0.207470
c    1.046727
d   -1.273295
e    1.001514
Name: p, dtype: float64

In [ ]:
df[['p','s']] 

p         s
a -1.276265  0.055988
b -0.207470 -0.392833
c  1.046727 -0.272427
d -1.273295  1.434853
e  1.001514  0.180338

In [ ]:
df.loc['d']

p   -1.273295
q    0.558726
r   -0.784153
s    1.434853
t    0.587968
Name: d, dtype: float64

In [ ]:
df.loc[0]

KeyError: ignored

In [ ]:
df.iloc[0]

p   -1.276265
q   -0.441164
r    1.088538
s    0.055988
t   -0.812554
Name: a, dtype: float64

In [ ]:
df.iloc[1] #grabbing the first row, i can either grab it by loc or iloc
# iloc going to ask the indix ( 0,1,2,3,4 etc...)

p   -0.207470
q    0.464722
r   -0.704728
s   -0.392833
t    1.024017
Name: b, dtype: float64

In [ ]:
df.loc[['a','b'],['p','q']]
# I can get 2*2 elements from this dataframe

p         q
a -1.276265 -0.441164
b -0.207470  0.464722

In [ ]:
df.loc[['b','d','e'],['q','s']]

q         s
b  0.464722 -0.392833
d  0.558726  1.434853
e  0.213916  0.180338

In [ ]:
df.iloc[0:2,0:2]

p         q
a -1.276265 -0.441164
b -0.207470  0.464722

In [ ]:
df.iloc[0:4,0:4]

p         q         r         s
a -1.276265 -0.441164  1.088538  0.055988
b -0.207470  0.464722 -0.704728 -0.392833
c  1.046727  0.369640 -0.859729 -0.272427
d -1.273295  0.558726 -0.784153  1.434853

In [ ]:
df>0

p      q      r      s      t
a  False  False   True   True  False
b  False   True  False  False   True
c   True   True  False  False  False
d  False   True  False   True   True
e   True   True   True   True  False

In [ ]:
df[df>0]

p         q         r         s         t
a       NaN       NaN  1.088538  0.055988       NaN
b       NaN  0.464722       NaN       NaN  1.024017
c  1.046727  0.369640       NaN       NaN       NaN
d       NaN  0.558726       NaN  1.434853  0.587968
e  1.001514  0.213916  0.417707  0.180338       NaN

In [ ]:
df[df==0]

p   q   r   s   t
a NaN NaN NaN NaN NaN
b NaN NaN NaN NaN NaN
c NaN NaN NaN NaN NaN
d NaN NaN NaN NaN NaN
e NaN NaN NaN NaN NaN

In [ ]:
np.random.rand(5,1)

array([[0.50409069],
       [0.25954741],
       [0.46510442],
       [0.8553662 ],
       [0.43573491]])

In [ ]:
df['u']=np.random.randn(5,1)

In [ ]:
df

p         q         r         s         t         u
a -1.276265 -0.441164  1.088538  0.055988 -0.812554 -1.394389
b -0.207470  0.464722 -0.704728 -0.392833  1.024017 -1.281944
c  1.046727  0.369640 -0.859729 -0.272427 -0.595269  1.184987
d -1.273295  0.558726 -0.784153  1.434853  0.587968 -0.226635
e  1.001514  0.213916  0.417707  0.180338 -0.784085 -1.670345

In [ ]:
df.drop('a')

p         q         r         s         t         u
b -0.207470  0.464722 -0.704728 -0.392833  1.024017 -1.281944
c  1.046727  0.369640 -0.859729 -0.272427 -0.595269  1.184987
d -1.273295  0.558726 -0.784153  1.434853  0.587968 -0.226635
e  1.001514  0.213916  0.417707  0.180338 -0.784085 -1.670345

In [ ]:
df.drop('u',axis=1)

p         q         r         s         t
a -1.276265 -0.441164  1.088538  0.055988 -0.812554
b -0.207470  0.464722 -0.704728 -0.392833  1.024017
c  1.046727  0.369640 -0.859729 -0.272427 -0.595269
d -1.273295  0.558726 -0.784153  1.434853  0.587968
e  1.001514  0.213916  0.417707  0.180338 -0.784085

In [ ]:
df

p         q         r         s         t         u
a -1.276265 -0.441164  1.088538  0.055988 -0.812554 -1.394389
b -0.207470  0.464722 -0.704728 -0.392833  1.024017 -1.281944
c  1.046727  0.369640 -0.859729 -0.272427 -0.595269  1.184987
d -1.273295  0.558726 -0.784153  1.434853  0.587968 -0.226635
e  1.001514  0.213916  0.417707  0.180338 -0.784085 -1.670345

In [ ]:
# we have dropped the a and u temporarily
# in order to drop any thing permanantly we have to use inplace=tru
df.drop('u',axis=1,inplace=True)


In [ ]:
df

p         q         r         s         t
a -1.276265 -0.441164  1.088538  0.055988 -0.812554
b -0.207470  0.464722 -0.704728 -0.392833  1.024017
c  1.046727  0.369640 -0.859729 -0.272427 -0.595269
d -1.273295  0.558726 -0.784153  1.434853  0.587968
e  1.001514  0.213916  0.417707  0.180338 -0.784085

In [ ]:
df.drop(['p','q'],axis=1)

r         s         t
a  1.088538  0.055988 -0.812554
b -0.704728 -0.392833  1.024017
c -0.859729 -0.272427 -0.595269
d -0.784153  1.434853  0.587968
e  0.417707  0.180338 -0.784085

In [ ]:
# reset the previous indices i dont want a,b,c,d,e
df.reset_index(inplace=True)


In [ ]:
df

p         q         r         s         t
a -1.276265 -0.441164  1.088538  0.055988 -0.812554
b -0.207470  0.464722 -0.704728 -0.392833  1.024017
c  1.046727  0.369640 -0.859729 -0.272427 -0.595269
d -1.273295  0.558726 -0.784153  1.434853  0.587968
e  1.001514  0.213916  0.417707  0.180338 -0.784085

In [ ]:
df

index         p         q         r         s         t
0     a -1.276265 -0.441164  1.088538  0.055988 -0.812554
1     b -0.207470  0.464722 -0.704728 -0.392833  1.024017
2     c  1.046727  0.369640 -0.859729 -0.272427 -0.595269
3     d -1.273295  0.558726 -0.784153  1.434853  0.587968
4     e  1.001514  0.213916  0.417707  0.180338 -0.784085

In [3]:
# Self Practice_Class1
import pandas as pd
import numpy as np

In [10]:
list1=[1,4,5,6,5,8]
# convert into lsit1 into an array

array=np.array(list1)


In [5]:
d

array([1, 4, 5, 6, 5, 8])

In [7]:
#Covert the above list into a pandas series
series1=pd.Series(list1)

In [8]:
series1

0    1
1    4
2    5
3    6
4    5
5    8
dtype: int64

In [11]:
series2=pd.Series(array)

In [12]:
series2

0    1
1    4
2    5
3    6
4    5
5    8
dtype: int64

In [13]:
# fetching elements 

series1[2:]

2    5
3    6
4    5
5    8
dtype: int64

In [14]:
# We can create our own indices and column

indices=['a','b','c','d','e','f']

pd.Series(data=list1,index=indices)

a    1
b    4
c    5
d    6
e    5
f    8
dtype: int64

In [15]:
pd.Series(list1,indices)

a    1
b    4
c    5
d    6
e    5
f    8
dtype: int64

In [18]:
#pd.concat([series1,series2])
pd.concat([series1,series2],axis=1)

0  1
0  1  1
1  4  4
2  5  5
3  6  6
4  5  5
5  8  8

In [19]:
np.random.randn(5,5)

array([[-1.15516911, -0.81207428, -0.21406073, -1.05915522, -0.64296467],
       [ 0.19479224,  0.14837356, -0.15594544,  0.20470456,  1.60214475],
       [-0.62065945, -1.13351021,  0.08055656, -0.56387229,  0.314986  ],
       [ 0.23067164,  0.88397758,  0.60950875, -1.09816597,  1.01144986],
       [-0.26491787, -0.45591773,  1.5549164 ,  1.24198633, -0.0275327 ]])

In [21]:
# i want to convert array into DataFrame 

df=pd.DataFrame(np.random.randn(5,5))

In [24]:
df=pd.DataFrame(np.random.randn(5,5),index=['a','b','c','d','e'],columns=['p','q','r','s','t'])


In [25]:
df

p         q         r         s         t
a  0.233800  0.812989 -0.298136 -1.037413  0.278548
b -0.158911 -1.579772 -0.205421 -0.822126  0.432848
c  0.425167  1.392460 -0.141157  0.577772  1.104595
d -0.569529 -0.453976  0.179962  0.028925 -0.940969
e  1.063263 -0.402888  0.150140 -0.657442  2.091428

In [27]:
df["p"]

a    0.233800
b   -0.158911
c    0.425167
d   -0.569529
e    1.063263
Name: p, dtype: float64

In [31]:
df.iloc[0]

p    0.233800
q    0.812989
r   -0.298136
s   -1.037413
t    0.278548
Name: a, dtype: float64

In [32]:
df.iloc[0:]

p         q         r         s         t
a  0.233800  0.812989 -0.298136 -1.037413  0.278548
b -0.158911 -1.579772 -0.205421 -0.822126  0.432848
c  0.425167  1.392460 -0.141157  0.577772  1.104595
d -0.569529 -0.453976  0.179962  0.028925 -0.940969
e  1.063263 -0.402888  0.150140 -0.657442  2.091428

In [36]:
df.loc[['a']]

p         q         r         s         t
a  0.2338  0.812989 -0.298136 -1.037413  0.278548

In [37]:
df.loc[['a','b'],['p','q']]

p         q
a  0.233800  0.812989
b -0.158911 -1.579772

TypeError: ignored