Write a NumPy program to compute the multiplication of two given matrices

In [ ]:
matrix1 = [[12,7,3],
        [4 ,5,6],
        [7 ,8,9]]
matrix2 = [[5,8,1],
        [6,7,3],
        [4,5,9]]
 
res = [[0 for x in range(3)] for y in range(3)]
 
# explicit for loops
for i in range(len(matrix1)):
    for j in range(len(matrix2[0])):
        for k in range(len(matrix2)):
 
            # resulted matrix
            res[i][j] += matrix1[i][k] * matrix2[k][j]
 
print (res)

[[114, 160, 60], [74, 97, 73], [119, 157, 112]]


2. Write a NumPy program to compute the outer product of two given vectors.

In [ ]:
import numpy as np
  
# Creating two 3-D matrix
matrix1 = np.array([[2, 8, 2], [3, 4, 8], [0, 2, 1]])
matrix2 = np.array([[2, 1, 1], [0, 1, 0], [2, 3, 0]])
print("Original 3-D matrix:")
print(matrix1)
print(matrix2)
  
# Output
print("Outer Product of the two matrix is:")
result = np.outer(matrix1, matrix2)
print(result)

Original 3-D matrix:
[[2 8 2]
 [3 4 8]
 [0 2 1]]
[[2 1 1]
 [0 1 0]
 [2 3 0]]
Outer Product of the two matrix is:
[[ 4  2  2  0  2  0  4  6  0]
 [16  8  8  0  8  0 16 24  0]
 [ 4  2  2  0  2  0  4  6  0]
 [ 6  3  3  0  3  0  6  9  0]
 [ 8  4  4  0  4  0  8 12  0]
 [16  8  8  0  8  0 16 24  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 4  2  2  0  2  0  4  6  0]
 [ 2  1  1  0  1  0  2  3  0]]


3. Write a NumPy program to compute the cross product of two given vectors

In [ ]:
import numpy as np
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print("original matrix:")
print(p)
print(q)
result1 = np.cross(p, q)
result2 = np.cross(q, p)
print("cross product of the said two vectors(p, q):")
print(result1)
print("cross product of the said two vectors(q, p):")
print(result2)

original matrix:
[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
cross product of the said two vectors(p, q):
[ 2 -3]
cross product of the said two vectors(q, p):
[-2  3]


4. Write a NumPy program to compute the determinant of a given square array.


In [ ]:
import numpy as np
from numpy import linalg
  
# Creating a 2X2 matrix
matrix = np.array([[1, 0], [3, 6]])
print("Original 2-D matrix")
print(matrix)
  
# Output
print("Determinant of the 2-D matrix:")
print(np.linalg.det(matrix))

Original 2-D matrix
[[1 0]
 [3 6]]
Determinant of the 2-D matrix:
6.0


5. Write a NumPy program to evaluate Einstein's summation convention of two given
multidimensional arrays.


In [ ]:
import numpy as np
  
# Creating two 2X2 matrix
matrix1 = np.array([[1, 2], [0, 2]])
matrix2 = np.array([[0, 1], [3, 4]])
  
print("Original matrix:")
print(matrix1)
print(matrix2)
  
# Output
result = np.einsum("mk,kn", matrix1, matrix2)
  
print("Einstein’s summation convention of the two matrix:")
print(result)

Original matrix:
[[1 2]
 [0 2]]
[[0 1]
 [3 4]]
Einstein’s summation convention of the two matrix:
[[6 9]
 [6 8]]


Write a NumPy program to compute the inner product of vectors for 1-D arrays (without
complex conjugation)
and in higher dimension

In [ ]:
import numpy as np
a = np.array([1,2,5])
b = np.array([2,1,0])
print("Original 1-d arrays:")
print(a)
print(b)
print 
result = np.inner(a, b)
print("Inner product of the said vectors:")
x = np.arange(9).reshape(3, 3)
y = np.arange(3, 12).reshape(3, 3)
print("Higher dimension arrays:")
print(x)
print(y)
result = np.inner(x, y)
print("Inner product of the said vectors:")
print(result)

Original 1-d arrays:
[1 2 5]
[2 1 0]
Inner product of the said vectors:
Higher dimension arrays:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Inner product of the said vectors:
[[ 14  23  32]
 [ 50  86 122]
 [ 86 149 212]]


7. Write a NumPy program to compute the eigenvalues and right eigenvectors of a given
square array

In [ ]:
import numpy as np
m = np.mat("3 -2;1 0")
print("Original matrix:")
print("a\n", m)
w, v = np.linalg.eig(m) 
print( "Eigenvalues of the said matrix",w)
print( "Eigenvectors of the said matrix",v)

Original matrix:
a
 [[ 3 -2]
 [ 1  0]]
Eigenvalues of the said matrix [2. 1.]
Eigenvectors of the said matrix [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


8. Write a NumPy program to compute the Kronecker product of two given mulitdimension
arrays.

In [ ]:
import numpy
 
# Creating arrays
array1 = numpy.array([[1, 2, 3], [4, 5, 6]])
print('Array1:\n', array1)
 
array2 = numpy.array([[1, 2], [3, 4], [5, 6]])
print('\nArray2:\n', array2)
 
# Computing the Kronecker Product
kroneckerProduct = numpy.kron(array1, array2)
print('\nArray1 ⊗ Array2:')
print(kroneckerProduct)

Array1:
 [[1 2 3]
 [4 5 6]]

Array2:
 [[1 2]
 [3 4]
 [5 6]]

Array1 ⊗ Array2:
[[ 1  2  2  4  3  6]
 [ 3  4  6  8  9 12]
 [ 5  6 10 12 15 18]
 [ 4  8  5 10  6 12]
 [12 16 15 20 18 24]
 [20 24 25 30 30 36]]


9. Write a NumPy program to compute the condition number of a given matrix.


In [ ]:
import numpy as np
  
# Creating a 2X2 matrix
matrix = np.array([[4, 2], [3, 1]])
  
print("Original matrix:")
print(matrix)
  
# Output
result =  np.linalg.cond(matrix)
  
print("Condition number of the matrix:")
print(result)

Original matrix:
[[4 2]
 [3 1]]
Condition number of the matrix:
14.933034373659256


10. Write a NumPy program to find a matrix or vector norm.

In [ ]:
import numpy as np
v = np.arange(7)
result = np.linalg.norm(v)
print("Vector norm:")
print(result)
m = np.matrix('1, 2; 3, 4') 
result1 = np.linalg.norm(m)
print("Matrix norm:")
print(result1)

Vector norm:
9.539392014169456
Matrix norm:
5.477225575051661


11. Write a NumPy program to compute the determinant of an array

In [ ]:
import numpy as np
a = np.array([[1,2],[3,4]])
print("Original array:")
print(a)
result =  np.linalg.det(a)
print("Determinant of the said array:")
print(result)

Original array:
[[1 2]
 [3 4]]
Determinant of the said array:
-2.0000000000000004


12. Write a NumPy program to compute the inverse of a given matrix.

In [ ]:
import numpy as np
m = np.array([[1,2],[3,4]])
print("Original matrix:")
print(m)
result =  np.linalg.inv(m)
print("Inverse of the said matrix:")
print(result)

Original matrix:
[[1 2]
 [3 4]]
Inverse of the said matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]


13. Write a NumPy program to calculate the QR decomposition of a given matrix.

In [ ]:
arr = np.array([[5, 11, -15], [12, 34, -51], 
                [-24, -43, 92]], dtype=np.int32) 
    
print(arr)
  
# Find the QR factor of array 
q, r = np.linalg.qr(arr) 
print('\nQ:\n', q)
print('\nR:\n', r)

[[  5  11 -15]
 [ 12  34 -51]
 [-24 -43  92]]

Q:
 [[-0.18318583 -0.08610905  0.97929984]
 [-0.43964598 -0.88381371 -0.15995231]
 [ 0.87929197 -0.45984624  0.12404465]]

R:
 [[-27.29468813 -54.77256208 106.06459346]
 [  0.         -11.22347731   4.06028083]
 [  0.           0.           4.88017756]]


14. Write a NumPy program to compute the condition number of a given matrix

In [ ]:
import numpy as np
m = np.array([[1,2],[3,4]])
print("Original matrix:")
print(m)
result =  np.linalg.cond(m)
print("Condition number of the said matrix:")
print(result)

Original matrix:
[[1 2]
 [3 4]]
Condition number of the said matrix:
14.933034373659268


15. Write a NumPy program to compute the sum of the diagonal element of a given array

In [ ]:
import numpy as np
  
# creating a 5X5 Numpy matrix
n_array = np.array([[5, 2, 1, 4, 6],
                    [9, 4, 2, 5, 2],
                    [11, 5, 7, 3, 9],
                    [5, 6, 6, 7, 2],
                    [7, 5, 9, 3, 3]])
  
# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)
  
# Finding the diagonal elements of a matrix
diag = np.diagonal(n_array)
  
print("\nDiagonal elements are:")
print(diag)
  
print("\nSum of Diagonal elements is:")
print(sum(diag))

Numpy Matrix is:
[[ 5  2  1  4  6]
 [ 9  4  2  5  2]
 [11  5  7  3  9]
 [ 5  6  6  7  2]
 [ 7  5  9  3  3]]

Diagonal elements are:
[5 4 7 7 3]

Sum of Diagonal elements is:
26
