In [ ]:
#1. Write a NumPy program to compute the multiplication of two given matrices.
import numpy as np
n1=np.array([[1,2,3],[3,4,5],[7,8,9]])
n2=np.array([[3,4,6],[5,6,4],[8,3,0]])
print(n1*n2)


[[ 3  8 18]
 [15 24 20]
 [56 24  0]]


In [ ]:
#2. Write a NumPy program to compute the outer product of two given vectors.
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
r=np.outer(p,q)
r

array([[1, 2, 3, 4],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 2, 3, 4]])

In [ ]:
#3. Write a NumPy program to compute the cross product of two given vectors.
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
result1 = np.cross(p, q)
result2 = np.cross(q, p)   #(a1, a2, a3) X (b1, b2, b3) = (a2*b3-a3*b2, a3*b1-a1*b3, a1*b2-a2*b1)
print(result1)
print(result2)


[ 2 -3]
[-2  3]


In [ ]:
#4. Write a NumPy program to compute the determinant of a given square array
from numpy import linalg as LA
a = np.array([[1, 0], [1, 2]])
print("Original 2-d array")
print(a)
print("Determinant of the said 2-D array:")
print(np.linalg.det(a))

Original 2-d array
[[1 0]
 [1 2]]
Determinant of the said 2-D array:
2.0


In [ ]:
#5. Write a NumPy program to evaluate Einstein's summation convention of two given
#multidimensional arrays.
matrix1 = np.array([[1, 2], [0, 2]])
matrix2 = np.array([[0, 1], [3, 4]])
  
print("Original matrix:")
print(matrix1)
print(matrix2)
  
# Output
result = np.einsum("mk,kn", matrix1, matrix2)
  
print("Einstein’s summation convention of the two matrix:")
print(result)

Original matrix:
[[1 2]
 [0 2]]
[[0 1]
 [3 4]]
Einstein’s summation convention of the two matrix:
[[6 9]
 [6 8]]


In [ ]:
#6. Write a NumPy program to compute the inner product of vectors for 1-D arrays (without
#complex conjugation) and in higher dimension.

a = np.array([1,2,5])
b = np.array([2,1,0])
print("Original 1-d arrays:")
print(a)
print(b)
print 
result = np.inner(a, b)
print("Inner product of the said vectors:")
x = np.arange(9).reshape(3, 3)
y = np.arange(3, 12).reshape(3, 3)
print("Higher dimension arrays:")
print(x)
print(y)
result = np.inner(x, y)
print("Inner product of the said vectors:")
print(result)

In [ ]:
#7. Write a NumPy program to compute the eigenvalues and right eigenvectors of a given square array.

import numpy as np
m = np.mat("3 -2;1 0")
print("Original matrix:")
print("a\n", m)
w, v = np.linalg.eig(m) 
print( "Eigenvalues of the said matrix",w)
print( "Eigenvectors of the said matrix",v)

In [ ]:
#8. Write a NumPy program to compute the Kronecker product of two given mulitdimension arrays.
import numpy
 
# Creating arrays
array1 = numpy.array([[1, 2, 3], [4, 5, 6]])
print('Array1:\n', array1)
 
array2 = numpy.array([[1, 2], [3, 4], [5, 6]])
print('\nArray2:\n', array2)
 
# Computing the Kronecker Product
kroneckerProduct = numpy.kron(array1, array2)
print('\nArray1 ⊗ Array2:')
print(kroneckerProduct)

In [ ]:
#9. Write a NumPy program to compute the condition number of a given matrix.
import numpy as np
  
# Creating a 2X2 matrix
matrix = np.array([[4, 2], [3, 1]])
  
print("Original matrix:")
print(matrix)
  
# Output
result =  np.linalg.cond(matrix)
  
print("Condition number of the matrix:")
print(result)

In [ ]:
#10. Write a NumPy program to find a matrix or vector norm.
import numpy as np
v = np.arange(7)
result = np.linalg.norm(v)
print("Vector norm:")
print(result)
m = np.matrix('1, 2; 3, 4') 
result1 = np.linalg.norm(m)
print("Matrix norm:")
print(result1)

In [ ]:
#11. Write a NumPy program to compute the determinant of an array.

import numpy as np
a = np.array([[1,2],[3,4]])
print("Original array:")
print(a)
result =  np.linalg.det(a)
print("Determinant of the said array:")
print(result)

In [ ]:
#12. Write a NumPy program to compute the inverse of a given matrix.
import numpy as np
m = np.array([[1,2],[3,4]])
print("Original matrix:")
print(m)
result =  np.linalg.inv(m)
print("Inverse of the said matrix:")
print(result)

In [ ]:
#13. Write a NumPy program to calculate the QR decomposition of a given matrix.

arr = np.array([[5, 11, -15], [12, 34, -51], 
                [-24, -43, 92]], dtype=np.int32) 
    
print(arr)
  
# Find the QR factor of array 
q, r = np.linalg.qr(arr) 
print('\nQ:\n', q)
print('\nR:\n', r)

In [ ]:
#14. Write a NumPy program to compute the condition number of a given matrix.
import numpy as np
m = np.array([[1,2],[3,4]])
print("Original matrix:")
print(m)
result =  np.linalg.cond(m)
print("Condition number of the said matrix:")
print(result)

In [ ]:
#15. Write a NumPy program to compute the sum of the diagonal element of a given array.
import numpy as np
  
# creating a 5X5 Numpy matrix
n_array = np.array([[5, 2, 1, 4, 6],
                    [9, 4, 2, 5, 2],
                    [11, 5, 7, 3, 9],
                    [5, 6, 6, 7, 2],
                    [7, 5, 9, 3, 3]])
  
# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)
  
# Finding the diagonal elements of a matrix
diag = np.diagonal(n_array)
  
print("\nDiagonal elements are:")
print(diag)
  
print("\nSum of Diagonal elements is:")
print(sum(diag))